### ISSUE TITLE
required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by phxuecan** [pinax/pinax-points#18]
target_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name="awardedpointvalue_targets")
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by jaydenwindle** [comment]
The version of pinax-points on pypi is currently v0.4, but Django 2.0 support was added in v0.7.

If you install directly from this repo (`pip install -e git://github.com/pinax/pinax-points.git@7e8da1b0dc475863e737fe9d921c7ffe70c37667#egg=pinax_points`) that should fix your issue temporarily until a new release is added to pypi.

**Comment by jtauber** [comment]
Sorry, we'll get it published to PyPI soon.

**Comment by KatherineMichel** [comment]
Closing issue because was resolved through 1.0 release. https://pypi.org/project/pinax-points/1.0/#history
